name: Update Calendar

on:
  schedule:
    - cron: '0 7-21/1 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run calendar builder
        run: python ptac_sync.py --with-addresses

      - name: Commit updates
        run: |
          git config --global user.name "calendar-bot"
          git config --global user.email "bot@example.com"
          git add output/*
          git commit -m "Calendar update" || echo "No changes"
          git push
